<a href="https://colab.research.google.com/github/aloreggia/vorace/blob/main/vorace_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!cp "/content/drive/MyDrive/vorace/Vorace.py" .

In [ ]:
 
!pip install keras==2.2.4

In [ ]:
!pip install corankco

     |████████████████████████████████| 3.2MB 7.6MB/s 
     |████████████████████████████████| 40.6MB 94kB/s 
  Created wheel for bioconsertinc: filename=bioconsertinc-0.1.0-cp37-cp37m-linux_x86_64.whl size=28638 sha256=f98d43a3a9c46df6d0951421d9c587d44df0686ae1bae90b4bc2b9b27738bd6f
  Stored in directory: /root/.cache/pip/wheels/13/7d/42/e242d80f4c4f890b0ede5666cbb9d9d4d19da9ed40f8ffdfee
Successfully built bioconsertinc


In [ ]:
 
 
!pip uninstall --yes keras
!pip install keras==2.2.4
 
import os
 
os.environ["KERAS_BACKEND"] = "theano"
import keras.backend 
#keras.backend.set_image_dim_ordering('th')
 
from Vorace import Vorace
from keras.callbacks import EarlyStopping
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
 
df = load_iris(return_X_y=True)

Uninstalling Keras-2.2.4:
  Successfully uninstalled Keras-2.2.4
  Using cached https://files.pythonhosted.org/packages/5e/10/aa32dad071ce52b5502266b5c659451cfd6ffcbf14e6c8c4f16c0ff5aaab/Keras-2.2.4-py2.py3-none-any.whl


In [ ]:
earlystop = EarlyStopping(monitor='acc', min_delta=0.001, patience=3, verbose=0, mode='auto')
callbacks_list = [earlystop]


Create a new instance of Vorace with 10 classifiers.
Based on type, ensemble are made of:


*   type 0: neural networks
*   type 1: decision trees
*   type 2: SVMs
*   type 3: mixed ensmbles



In [ ]:
vorace = Vorace(n_models=10, profile_type=2, nInput=4, nClasses=3, batch_size=16)

In [ ]:
X = df[0]
y = df[1]
y = np.asarray(y)
y=y.reshape(-1,)
y_oneHot=to_categorical(y,num_classes=3)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50, random_state=42)

In [ ]:
y_oneHot=to_categorical(y_train,num_classes=3)
y_train
 
y_oneHot_test=to_categorical(y_test,num_classes=3)

In [ ]:
vorace.fit(X_train, y_train, y_oneHot, bagging=False)

In [ ]:
y_pred_vorace,_ = vorace.predict(voting="Plurality",x=X_test,y=y_test, nClasses=3, argMax=True, tiebreak="best")
print(y_pred_vorace)
print(y_test)
#predictions = np.argmax(y_pred_vorace,axis=1)
accuracy = accuracy_score(y_test, y_pred_vorace)
print(accuracy)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0 1 1 2 1 2 1 2 1 0 2 1 0 0 0 1 2 0 0 0 1 0 1 2 0 1 2 0 1 2
 1]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0 1 2 2 1 2 1 2 1 0 2 1 0 0 0 1 2 0 0 0 1 0 1 2 0 1 2 0 2 2
 1]
0.9733333333333334


In [ ]:
conf_mat = confusion_matrix(y_test, y_pred_vorace)
print(conf_mat)

[[29  0  0]
 [ 0 20  3]
 [ 0  3 20]]
