<a href="https://colab.research.google.com/github/aloreggia/vorace/blob/main/vorace_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from Vorace import Vorace
from keras.callbacks import EarlyStopping
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
 
df = load_iris(return_X_y=True)

Create a new instance of Vorace with 10 classifiers.
Based on type, ensemble are made of:


*   type 0: neural networks
*   type 1: decision trees
*   type 2: SVMs
*   type 3: mixed ensmbles



In [ ]:
vorace = Vorace(n_models=10, profile_type=2, nInput=4, nClasses=3, batch_size=16)

In [ ]:
X = df[0]
y = df[1]
y = np.asarray(y)
y=y.reshape(-1,)
y_oneHot=to_categorical(y,num_classes=3)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50, random_state=42)

In [ ]:
y_oneHot=to_categorical(y_train,num_classes=3)
y_train
 
y_oneHot_test=to_categorical(y_test,num_classes=3)

In [ ]:
vorace.fit(X_train, y_train, y_oneHot, bagging=False)

In [ ]:
y_pred_vorace,_ = vorace.predict(voting="Plurality",x=X_test,y=y_test, nClasses=3, argMax=True, tiebreak="best")
print(y_pred_vorace)
print(y_test)
#predictions = np.argmax(y_pred_vorace,axis=1)
accuracy = accuracy_score(y_test, y_pred_vorace)
print(accuracy)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0 1 1 2 1 2 1 2 1 0 2 1 0 0 0 1 2 0 0 0 1 0 1 2 0 1 2 0 1 2
 1]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0 1 2 2 1 2 1 2 1 0 2 1 0 0 0 1 2 0 0 0 1 0 1 2 0 1 2 0 2 2
 1]
0.9733333333333334


In [ ]:
conf_mat = confusion_matrix(y_test, y_pred_vorace)
print(conf_mat)

[[29  0  0]
 [ 0 20  3]
 [ 0  3 20]]
